services:
  backend:
    build:
      context: ./backend
    container_name: ies-backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend/src:/app/src
    env_file:
      - ./backend/.env
    depends_on:
      - postgres
      - kafka
    restart: always

  frontend:
    build:  
      context: ./frontend
    container_name: ies-frontend
    ports:
      - "3000:3000"
    volumes:  
      - ./frontend/src:/app/src
    environment:
      - CHOKIDAR_USEPOLLING=true  
    restart: always
    command: npm run dev

  postgres:
    image: postgres:latest
    container_name: ies-postgres
    environment:
      POSTGRES_USER: ies_admin
      POSTGRES_PASSWORD: ies_password
      POSTGRES_DB: ies_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: ies-zookeeper
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
    ports:
      - "2181:2181"
    restart: always

  kafka:
    image: bitnami/kafka:latest
    container_name: ies-kafka
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_CFG_ZOOKEEPER_CONNECT: ies-zookeeper:2181
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://ies-kafka:9092
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    restart: always

volumes:
  postgres_data:
